### DISCUSSION TITLE
How to sign commits made by nyx?

### DISCUSSION THREAD

**Discussion by lengors** [mooltiverse/nyx#284] [Q&A]
I'm attempting to create a release with nyx and I want the commits made by it signed. For this I tried the following GitHub action:
```yaml
name: Release to GitHub

on:
  workflow_dispatch:

jobs:
  publish:
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v1
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Publish release
        id: nyx
        run: ./gradlew release --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
      - name: Published version info
        if: ${{ steps.nyx.outputs.version != '' }}
        run: echo New version is ${{ steps.nyx.outputs.version }}
      - name: Version not published info
        if: ${{ steps.nyx.outputs.version == '' }}
        run: echo Version not published
```

My nyx configuration file looks like this:
```yaml
---
preset: extended
initialVersion: 0.0.0

commitMessageConventions:
  enabled:
    - gitmoji

git:
  remotes:
    origin:
      authenticationMethod: USER_PASSWORD
      user: "{{#environmentVariable}}GITHUB_TOKEN{{/environmentVariable}}"
      password: "{{#environmentVariable}}GITHUB_TOKEN{{/environmentVariable}}"

releaseTypes:
  enabled:
    - mainline
    - maturity
    - integration
  publicationServices:
    - github
  remoteRepositories:
    - origin
  items:
    mainline:
      collapseVersions: false
      filterTags: "^({{configuration.releasePrefix}})?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)$"
      gitCommit: "true"
      gitPush: "true"
      gitPushForce: "true"
      gitTag: "true"
      gitTagForce: "true"
      matchBranches: "^(master|main)$"
      matchWorkspaceStatus: "CLEAN"
      publish: "true"
    maturity:
      collapseVersions: true
      collapsedVersionQualifier: "{{#sanitizeLower}}{{branch}}{{/sanitizeLower}}"
      filterTags: "^({{configuration.releasePrefix}})?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)(-(alpha|beta)(\\.([0-9]\\d*))?)?$"
      gitCommit: "true"
      gitPush: "true"
      gitPushForce: "true"
      gitTag: "true"
      gitTagForce: "true"
      matchBranches: "^(alpha|beta)$"
      matchWorkspaceStatus: "CLEAN"
      publish: "true"
      publishPreRelease: "true"
    integration:
      collapseVersions: true
      collapsedVersionQualifier: "{{#sanitizeLower}}{{branch}}{{/sanitizeLower}}"
      filterTags: "({{configuration.releasePrefix}})?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)(-(develop|development|integration|latest)(\\.([0-9]\\d*))?)$"
      gitCommit: "true"
      gitPush: "true"
      gitPushForce: "true"
      gitTag: "true"
      gitTagForce: "true"
      matchBranches: "^(develop|development|integration|latest)$"
      matchWorkspaceStatus: "CLEAN"
      publish: "true"
      publishPreRelease: "true"


services:
  github:
    type: "GITHUB"
    options:
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}GITHUB_TOKEN{{/environmentVariable}}"
      REPOSITORY_NAME: "test"
      REPOSITORY_OWNER: "lengors"
---
```

However, when running the GitHub action I get an error:
```
org.eclipse.jgit.api.errors.ServiceUnavailableException: Signing service is not available
```

It's related to JGit and I'm not sure if there's anything that I can do on "nyx's side" or if I would have to look into JGit's documentation.

I did try Nyx's GitHub action where the related section looks like this (same configuration file as above):
```yaml
      - name: Publish package
        id: nyx
        uses: mooltiverse/nyx-github-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
          NYX_VERBOSITY: "INFO"
        with:
          command: publish
          configurationFile: ".nyx.yaml"
```

But with this I don't even get a commit. Just the tag.

Is there a way to achieve commit signing with Nyx (and if so how?), is it not possible or would I have to look into JGit's documentation?
