### ISSUE TITLE
nyx mark - no version changes causes an error

### ISSUE THREAD

**Issue by abix5** [mooltiverse/nyx#152]
If there are commits that don't make version changes, `nyx mark` crashes with an error when trying to `git push` changes. If you run the same configuration with a commit that changes the version, everything works fine.

- [x] `nyx 2.0.0`

- .nyx.yml

```
changelog:
  path: ".CHANGELOG.md"
...
git:
  remotes:
    origin:
      user: "PRIVATE-TOKEN"
      password: "{{#environmentVariable}}GITLAB_TOKEN{{/environmentVariable}}"
commitMessageConventions: 
  enabled: 
    - conventionalCommits
  items: 
    conventionalCommits: 
...
initialVersion: "0.1.0"
releaseLenient: true
releasePrefix: "v"
releaseTypes:
  enabled: 
    - mainline
    - integration
    - feature
  publicationServices:
    - gitlab
  remoteRepositories:
    - origin
  items: 
    mainline: 
...
    integration: 
      collapseVersions: false
      description: "{{#fileContent}}.CHANGELOG.md{{/fileContent}}"
      filterTags: "^({{configuration.releasePrefix}})?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)(-(beta)(\\.([0-9]\\d*))?)$"
      gitCommit: "true"
      gitPush: "true"
      gitTag: "true"
      gitTagMessage: "{{#fileContent}}.CHANGELOG.md{{/fileContent}}"
      matchBranches: "^(dev|develop|development|integration|latest)$"
      matchEnvironmentVariables: 
        CI: "^true$"
      identifiers: 
        - position: PRE_RELEASE
          qualifier: beta
      publish: "true"
      versionRangeFromBranchName: false
    feature: 
...
scheme: "SEMVER"
resume: true
services:
  gitlab: 
    type: "GITLAB"
    options: 
      "BASE_URI": "{{#environmentVariable}}CI_API_V4_URL{{/environmentVariable}}"
      "AUTHENTICATION_TOKEN": "{{#environmentVariable}}GITLAB_TOKEN{{/environmentVariable}}"
      "REPOSITORY_NAME": "{{#environmentVariable}}CI_PROJECT_NAME{{/environmentVariable}}"
      "REPOSITORY_OWNER": "{{#environmentVariable}}CI_PROJECT_NAMESPACE{{/environmentVariable}}"
stateFile: ".nyx-state.yml"
verbosity: TRACE
```

- gitlab-ci.log

```
...
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the 'scheme' configuration option"
time="2023-02-01T14:41:31Z" level=trace msg="the 'scheme' configuration option value is: 'SEMVER'"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the 'releaseLenient' configuration option"
time="2023-02-01T14:41:31Z" level=trace msg="the 'releaseLenient' configuration option value is: 'true'"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the 'directory' configuration option"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the default 'directory' configuration option: '/builds/back/crm-backend'"
time="2023-02-01T14:41:31Z" level=trace msg="the 'directory' configuration option value is: '/builds/back/crm-backend'"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the 'version' configuration option"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the default 'version' configuration option: '<nil>'"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the default 'version' configuration option: '<nil>'"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the 'version' configuration option"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the default 'version' configuration option: '<nil>'"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the default 'version' configuration option: '<nil>'"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the 'version' configuration option"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the default 'version' configuration option: '<nil>'"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the default 'version' configuration option: '<nil>'"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the 'version' configuration option"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the default 'version' configuration option: '<nil>'"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the default 'version' configuration option: '<nil>'"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the 'version' configuration option"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the default 'version' configuration option: '<nil>'"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the default 'version' configuration option: '<nil>'"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the 'version' configuration option"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the default 'version' configuration option: '<nil>'"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the default 'version' configuration option: '<nil>'"
time="2023-02-01T14:41:31Z" level=trace msg="retrieving the 'scheme' configuration option"
time="2023-02-01T14:41:31Z" level=trace msg="the 'scheme' configuration option value is: 'SEMVER'"
time="2023-02-01T14:41:31Z" level=debug msg="attempting push to 'origin' using user name and password credentials."
time="2023-02-01T14:41:31Z" level=debug msg="pushing changes to remote repository 'origin' using username and password"
time="2023-02-01T14:41:31Z" level=debug msg="username and password authentication will use custom authentication options"
an error occurred when trying to push: authentication required
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: command terminated with exit code 1
```
