### ISSUE TITLE
Question on commitMessageConventions configuration

### ISSUE THREAD

**Issue by flyingfishflash** [mooltiverse/nyx#195]
I'm just trying to override the conventionalCommits defaults in order to have 'refactor' type commit bump the patch version. I can't get this to work for some reason. (removing my commitMessageConventions block and just using the preset works fine)

```yaml
---
# starting from the "simple" preset gives us:
# - the Conventional Commits convention
# - the "mainline" and "internal" release types (that we override here)
preset: "simple"
commitMessageConventions:
  enabled:
    - conventionalCommitsCustom
  conventionalCommitsCustom:
    expression: '(?m)^(?<type>[a-zA-Z0-9_]+)(!)?(\((?<scope>[a-z ]+)\))?:( (?<title>.+))$(?s).*'
    bumpExpressions:
      major: "(?s)(?m)^[a-zA-Z0-9_]+(!|.*^(BREAKING( |-)CHANGE: )).*"
      minor: "(?s)(?m)^feat(?!!|.*^(BREAKING( |-)CHANGE: )).*"
      patch: "(?s)(?m)^fix|^refactor(?!!|.*^(BREAKING( |-)CHANGE: )).*"
```

This configuration never applies the logic to the commits to determine if it's significant or not?

```
2f9646a (HEAD -> feature-nyx-version-management) refactor: nyx semantic-release
58f52cf (origin/main, origin/HEAD, gitea/main, main) Merge pull request 'refactor-dependencies' (#39) from refactor-dependencies into main
63fefcf (origin/refactor-dependencies, gitea/refactor-dependencies, refactor-dependencies) build(backend): gradle 8.1
5165eba refactor(backend): spring-security-test 6.0.3
901ad2a refactor(frontend): eslint-plugin-jsdoc 41.1.2
```

debug output:
```
[gregory@opti7080-1 ledger]$ nyx infer --dry-run=true --debug
DEBU[0000] selecting the command to run                 
DEBU[0000] command to run is INFER                      
DEBU[0000] Nyx.run(INFER)                               
DEBU[0000] Nyx.infer()                                  
DEBU[0000] running command 'INFER'                      
DEBU[0000] looking up command instance 'INFER' from cache 
DEBU[0000] no command instance 'INFER' found in cache   
DEBU[0000] creating new command instance 'INFER'        
DEBU[0000] instantiating the Git repository in '/home/gregory/repositories/ledger' 
DEBU[0000] instantiating the initial state              
DEBU[0000] new Infer command object                     
DEBU[0000] checking whether the Infer command is up to date 
DEBU[0000] the Infer command is not up to date because the internal state has no version yet or the state version doesn't match the version previously generated by Infer 
DEBU[0000] command 'INFER' is not up to date, running... 
DEBU[0000] running the Infer command...                 
DEBU[0000] clearing the state from Infer outputs        
DEBU[0000] resolving the release type among enabled ones 
DEBU[0000] evaluating release type: 'mainline'          
DEBU[0000] release type 'mainline' specifies a match branches template '^(master|main)$' that evaluates to regular expression: '^(master|main)$' 
DEBU[0000] current branch 'feature-nyx-version-management' not matched by release type 'mainline' matchBranches regular expression '^(master|main)$'. Skipping release type 'mainline' 
DEBU[0000] evaluating release type: 'internal'          
DEBU[0000] release type 'internal' does not specify any branch name requirement 
DEBU[0000] release type 'internal'  does not specify any environment variable requirement 
DEBU[0000] release type 'internal' does not specify any workspace status requirement 
DEBU[0000] release type 'internal' has been selected    
DEBU[0000] current Git branch is 'feature-nyx-version-management' 
DEBU[0000] walking the commit history...                
DEBU[0000] walking commit history. Start commit boundary is 'not defined'. End commit boundary is 'not defined' 
DEBU[0000] upon merge commits only the first parent is considered. 
DEBU[0000] repository latest commit in HEAD branch is '2f9646a6ed4e22c139234e2e5d2ed3d748da3ac1' 
DEBU[0000] retrieving tags for commit '2f9646a6ed4e22c139234e2e5d2ed3d748da3ac1' 
DEBU[0000] stepping by commit '2f9646a6ed4e22c139234e2e5d2ed3d748da3ac1' 
DEBU[0000] commit '2f9646a6ed4e22c139234e2e5d2ed3d748da3ac1' has '0' tags: '[]' 
DEBU[0000] commit '2f9646a6ed4e22c139234e2e5d2ed3d748da3ac1' has no valid version tags so it's added to the release scope 
DEBU[0000] trying to infer the identifier to bump based on the commit message of commit '2f9646a6ed4e22c139234e2e5d2ed3d748da3ac1' 
DEBU[0000] retrieving tags for commit '58f52cf8f1552f7ac65cdef9171b9696d735edcd' 
DEBU[0000] stepping by commit '58f52cf8f1552f7ac65cdef9171b9696d735edcd' 
DEBU[0000] commit '58f52cf8f1552f7ac65cdef9171b9696d735edcd' has '0' tags: '[]' 
DEBU[0000] commit '58f52cf8f1552f7ac65cdef9171b9696d735edcd' has no valid version tags so it's added to the release scope 
DEBU[0000] trying to infer the identifier to bump based on the commit message of commit '58f52cf8f1552f7ac65cdef9171b9696d735edcd' 
DEBU[0000] retrieving tags for commit 'd1da71923a813f7cf3c63eda9b5ae59bc326cbba' 
DEBU[0000] stepping by commit 'd1da71923a813f7cf3c63eda9b5ae59bc326cbba' 
DEBU[0000] commit 'd1da71923a813f7cf3c63eda9b5ae59bc326cbba' has '1' tags: '[v0.3.28]' 
DEBU[0000] evaluating tag 'v0.3.28': tag is a valid version according to the 'SEMVER' scheme and will be passed to the next evaluation steps. The tag is applied to commit 'd1da71923a813f7cf3c63eda9b5ae59bc326cbba' 
DEBU[0000] evaluating tag 'v0.3.28': tag is greater than previously selected previousVersion tag '<none>' and will be passed to the next evaluation steps. The tag is applied to commit 'd1da71923a813f7cf3c63eda9b5ae59bc326cbba' 
DEBU[0000] evaluating tag 'v0.3.28': the selected release type does not specify any additional filter for tags (or the tags filter template yields to an empty regular expression after evaluation) so the tag will be used as the previousVersion and the commit 'd1da71923a813f7cf3c63eda9b5ae59bc326cbba' is used as the previousVersionCommit 
DEBU[0000] evaluating tag 'v0.3.28': the selected release type uses collapsed versioning so the tag will be passed to the next evaluation steps to check if it's a valid primeVersion. The tag is applied to commit 'd1da71923a813f7cf3c63eda9b5ae59bc326cbba' 
DEBU[0000] evaluating tag 'v0.3.28': tag is a valid core version according to the 'SEMVER' scheme and the selected release type uses collapsed versioning so the tag will be passed to the next evaluation steps to check if it's a valid primeVersion. The tag is applied to commit 'd1da71923a813f7cf3c63eda9b5ae59bc326cbba' 
DEBU[0000] evaluating tag 'v0.3.28': tag is greater than previously selected primeVersion tag '<none>' so it will be used as the primeVersion and the commit 'd1da71923a813f7cf3c63eda9b5ae59bc326cbba' is used as the primeVersionCommit 
DEBU[0000] commit history walk interrupted by visitor   
DEBU[0000] walking the commit history finished. The release scope contains 2 commits. 
DEBU[0000] after scanning the commit history the previousVersion is 'v0.3.28' and the primeVersion is 'v0.3.28' 
DEBU[0000] significant commits (bumping identifiers) since the previousVersion are '0', while those since the primeVersion are '0' 
DEBU[0000] the release scope does not contain any significant commit since the prime version, only collapsed identifier 'internal' is bumped while core identifiers are not bumped on prime version: '0.3.28' 
DEBU[0000] bumping qualifier 'internal' on prime version '0.3.28' yields to '0.3.28-internal.1' 
DEBU[0000] the release scope does not contain any significant commit since the previous version, identifiers are not bumped on previous version: '0.3.28' 
DEBU[0000] the greatest version between '0.3.28-internal.1' and '0.3.28' is '0.3.28', which is the new (collapsed) version 
DEBU[0000] computed version is: '0.3.28'                
INFO[0000] Version: '0.3.28'                            
DEBU[0000] no version range check is required           
DEBU[0000] no version range check is performed          
DEBU[0000] version '0.3.28' did not require version range checks 
DEBU[0000] checking if version '0.3.28' is the latest in the repository 
DEBU[0000] retrieving all tags                          
DEBU[0000] version '0.3.28' is the latest in the repository since no newer version has been found 
DEBU[0000] storing the Infer command internal attributes to the State 
DEBU[0000] repository latest commit in HEAD branch is '2f9646a6ed4e22c139234e2e5d2ed3d748da3ac1' 
DEBU[0000] command 'INFER' finished.  
```

**Comment by flyingfishflash** [comment]
OK to close: 

I found the reason:

missing the 'items' key, this works:

```yaml
---
# starting from the "simple" preset gives us:
# - the Conventional Commits convention
# - the "mainline" and "internal" release types (that we override here)
preset: "simple"
commitMessageConventions:
  enabled:
    - conventionalCommitsCustom
  items:
    conventionalCommitsCustom:
      expression: '(?m)^(?<type>[a-zA-Z0-9_]+)(!)?(\((?<scope>[a-z ]+)\))?:( (?<title>.+))$(?s).*'
      bumpExpressions:
        major: "(?s)(?m)^[a-zA-Z0-9_]+(!|.*^(BREAKING( |-)CHANGE: )).*"
        minor: "(?s)(?m)^feat(?!!|.*^(BREAKING( |-)CHANGE: )).*"
        patch: "(?s)(?m)^fix|^refactor(?!!|.*^(BREAKING( |-)CHANGE: )).*"
```
