### ISSUE TITLE
Is there a way to use the docker image directly in GitLab CI?

### ISSUE THREAD

**Issue by rrzal** [mooltiverse/nyx#215]
For example, when using the docker executor, I want to use the nyx image directly:
```yml
infer-job:
  stage: infer
  tags: 
    - docker
   image: mooltiverse/nyx:latest
  before_script:
   ...
```
This way, I don't have to use shell executor or docker in docker with docker commands (which also requires me to authenticate through GitHub). Nyx has good support for GitHub action, but it doesn't seem to support GitLab CI that well.
