### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by fad3t** [mooltiverse/nyx#221]
Hello,

I've started using nyx recently and I came across the following error:
```
$ nyx --verbosity=DEBUG infer
<truncated>
DEBU[0000] retrieving tags for commit 'b5f5ec912aef9a959ad8cb9168f6dddb748d24f1'
DEBU[0000] stepping by commit 'b5f5ec912aef9a959ad8cb9168f6dddb748d24f1'
DEBU[0000] commit 'b5f5ec912aef9a959ad8cb9168f6dddb748d24f1' has '0' tags: '[]'
DEBU[0000] commit 'b5f5ec912aef9a959ad8cb9168f6dddb748d24f1' has no valid version tags so it's added to the release scope
DEBU[0000] trying to infer the identifier to bump based on the commit message of commit 'b5f5ec912aef9a959ad8cb9168f6dddb748d24f1'
DEBU[0000] evaluating commit 'b5f5ec912aef9a959ad8cb9168f6dddb748d24f1' against message convention 'conventionalCommits'
DEBU[0000] commit message convention 'conventionalCommits' doesn't match commit 'b5f5ec912aef9a959ad8cb9168f6dddb748d24f1', skipping
DEBU[0000] commit history walk reached the end
DEBU[0000] walking the commit history finished. The release scope contains 10 commits.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100ccf130]

goroutine 1 [running]:
github.com/mooltiverse/nyx/modules/go/nyx/command.(*Infer).scanRepository(0x140001ae780, 0x140000620e0, 0x0, 0x140000280cb, 0x0, 0x0, 0x0, 0x14000223fb0, {0x10144e4b0, 0x0, ...}, ...)
	/home/runner/work/nyx/nyx/modules/go/nyx/command/infer.go:406 +0x360
github.com/mooltiverse/nyx/modules/go/nyx/command.(*Infer).Run(0x140001ae780)
	/home/runner/work/nyx/nyx/modules/go/nyx/command/infer.go:1463 +0x31c
github.com/mooltiverse/nyx/modules/go/nyx.(*Nyx).runCommand(0x101412320?, {0x100ce3fa8, 0x5}, 0x1)
	/home/runner/work/nyx/nyx/modules/go/nyx/nyx.go:328 +0x450
github.com/mooltiverse/nyx/modules/go/nyx.(*Nyx).Infer(0x101412320?)
	/home/runner/work/nyx/nyx/modules/go/nyx/nyx.go:499 +0x64
github.com/mooltiverse/nyx/modules/go/nyx.(*Nyx).Run(0x1400001e1c0?, {0x100ce3fa8, 0x5})
	/home/runner/work/nyx/nyx/modules/go/nyx/nyx.go:449 +0x240
main.main()
	/home/runner/work/nyx/nyx/modules/go/nyx/main/main.go:120 +0x2c8
```

Here's my config file:
```yaml
---
dryRun: true
preset: "simple"
changelog:
  path: "CHANGELOG.md"
verbosity: "INFO"
releaseTypes:
  items:
    mainline:
      gitCommit: true
      gitPush: false
```

I'm not getting the error if I remove the `gitCommit` and `gitPush` attributes from the releaseType.
Note I'm working with a local repository (no remote configured) at the moment.

I'm using the latest version (2.4.0), but I'm getting the same behavior with 2.3.5.

Any idea where this might be coming from?

Thx,
Frederic

**Comment by flelli** [comment]
Hi @fad3t ,

it's a bug for sure. I'll investigate asap and get back to you

**Comment by flelli** [comment]
Hi @fad3t , I just published the hotfix as release [2.4.1-hotfix221.1](https://github.com/mooltiverse/nyx/releases/tag/2.4.1-hotfix221.1). Can you please give it a try before I merge to main?

**Comment by fad3t** [comment]
Hi @flelli, thanks! I'm now getting the following error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa25335]
goroutine 1 [running]:
github.com/mooltiverse/nyx/modules/go/nyx/command.(*Infer).fillStateMissingValuesWithDefaults(0xc00012d050?, 0xc0000ac750?)
	/home/runner/work/nyx/nyx/modules/go/nyx/command/infer.go:470 +0x175
github.com/mooltiverse/nyx/modules/go/nyx/command.(*Infer).Run(0xc00012d050)
	/home/runner/work/nyx/nyx/modules/go/nyx/command/infer.go:1469 +0x457
github.com/mooltiverse/nyx/modules/go/nyx.(*Nyx).runCommand(0x116a160?, {0xc2dd56, 0x5}, 0x1)
	/home/runner/work/nyx/nyx/modules/go/nyx/nyx.go:328 +0x442
github.com/mooltiverse/nyx/modules/go/nyx.(*Nyx).Infer(0x116a160?)
	/home/runner/work/nyx/nyx/modules/go/nyx/nyx.go:499 +0x65
github.com/mooltiverse/nyx/modules/go/nyx.(*Nyx).Make(0x116a160?)
	/home/runner/work/nyx/nyx/modules/go/nyx/nyx.go:520 +0x50
github.com/mooltiverse/nyx/modules/go/nyx.(*Nyx).Mark(0x116a160?)
	/home/runner/work/nyx/nyx/modules/go/nyx/nyx.go:547 +0x50
github.com/mooltiverse/nyx/modules/go/nyx.(*Nyx).Publish(0x116a160?)
	/home/runner/work/nyx/nyx/modules/go/nyx/nyx.go:574 +0x50
github.com/mooltiverse/nyx/modules/go/nyx.(*Nyx).Run(0xc000022190?, {0xc2e88f, 0x7})
	/home/runner/work/nyx/nyx/modules/go/nyx/nyx.go:458 +0x245
main.main()
	/home/runner/work/nyx/nyx/modules/go/nyx/main/main.go:120 +0x312
```
My config changed a bit:
```yaml
---
stateFile: ".nyx-state.json"
preset: "simple"
changelog:
  path: "CHANGELOG.md"
verbosity: "INFO"
scheme: "SEMVER"
initialVersion: "0.1.0"
releaseLenient: true
releasePrefix: "v"
git:
  remotes:
    origin:
      authenticationMethod: "USER_PASSWORD"
      user: "nyx"
      password: "{{#environmentVariable}}GITLAB_TOKEN{{/environmentVariable}}"
releaseTypes:
  enabled:
  - "mainline"
  publicationServices:
  - "gitlab"
  items:
    mainline:
      gitCommit: true
      gitTag: true
      gitPush: true
      publish: true
services:
  gitlab:
    type: "GITLAB"
    options:
      BASE_URI: "{{#environmentVariable}}CI_API_V4_URL{{/environmentVariable}}"
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}GITLAB_TOKEN{{/environmentVariable}}"
      REPOSITORY_NAME: "{{#environmentVariable}}CI_PROJECT_NAME{{/environmentVariable}}"
      REPOSITORY_OWNER: "{{#environmentVariable}}CI_PROJECT_NAMESPACE{{/environmentVariable}}"
```
