### ISSUE TITLE
Add changelog to the Git tag message

### ISSUE THREAD

**Issue by fad3t** [mooltiverse/nyx#224]
Hello,

I would like to add the changelog to the Git tag message, and I tried to use templates for this:
```yaml
releaseTypes:
  enabled:
  - "mainline"
  publicationServices:
  - "gitlab"
  items:
    mainline:
      matchBranches: "^(main|master)$"
      gitTag: true
      gitTagMessage: |
        Release version {{version}}

        {{changelog}}
```
However this doesn't render as expected:
```
Release version v0.4.3

{[%!s(*entities.Release=&amp;{0xc000468ec0 0xc000539b40 [0xc00053cba0]})]}
```
Is there an easy way to do this, or do I have to go through the sections/commits?

Thx,
Frederic
