### ISSUE TITLE
runtime error during infer command

### ISSUE THREAD

**Issue by fad3t** [mooltiverse/nyx#225]
Hi,

Got the following error while running `nyx publish`. This seems to happen during the `infer` phase.
Note I'm only getting the error when there are no significant changes (= version remains unchanged). If I'm committing features or bug fixes, nyx works just fine.

The error message:
```
<snip>
time="2023-05-29T13:40:10Z" level=debug msg="stepping by commit 'f7a70ae2303d76346d9396d2a34eeff963778e92'"
time="2023-05-29T13:40:10Z" level=debug msg="commit 'f7a70ae2303d76346d9396d2a34eeff963778e92' has '0' tags: '[]'"
time="2023-05-29T13:40:10Z" level=debug msg="commit history walk reached the end"
time="2023-05-29T13:40:10Z" level=debug msg="walking the commit history finished. The release scope contains 1 commits."
time="2023-05-29T13:40:10Z" level=debug msg="after scanning the commit history the previousVersion is 'v0.6.3'"
time="2023-05-29T13:40:10Z" level=debug msg="significant commits (bumping identifiers) since the previousVersion are '0'"
time="2023-05-29T13:40:10Z" level=debug msg="the commit history had no information about the primeVersion and primeVersionCommit but the release type doesn't use collapsed versioning, using the same values as the previousVersion and previousVersionCommit"
time="2023-05-29T13:40:10Z" level=debug msg="the release scope does not contain any significant commit since the previous version, version remains unchanged: '0.6.3'"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa27dba]
goroutine 1 [running]:
github.com/mooltiverse/nyx/modules/go/nyx/command.(*Infer).computeVersion(0xc0001af650, 0xc0001ae6c0, 0x11a06b0?, 0xc000031724, 0x0?, 0xc00012c750, {0xc0004922a8?, 0xc0001af650?, 0xc0001ae6c0?}, 0xc0004cba58, ...)
	/home/runner/work/nyx/nyx/modules/go/nyx/command/infer.go:814 +0x16ba
github.com/mooltiverse/nyx/modules/go/nyx/command.(*Infer).Run(0xc0001af650)
	/home/runner/work/nyx/nyx/modules/go/nyx/command/infer.go:1499 +0x825
github.com/mooltiverse/nyx/modules/go/nyx.(*Nyx).runCommand(0x116a140?, {0xc2dd56, 0x5}, 0x1)
	/home/runner/work/nyx/nyx/modules/go/nyx/nyx.go:328 +0x442
github.com/mooltiverse/nyx/modules/go/nyx.(*Nyx).Infer(0x116a140?)
	/home/runner/work/nyx/nyx/modules/go/nyx/nyx.go:499 +0x65
github.com/mooltiverse/nyx/modules/go/nyx.(*Nyx).Make(0x116a140?)
	/home/runner/work/nyx/nyx/modules/go/nyx/nyx.go:520 +0x50
github.com/mooltiverse/nyx/modules/go/nyx.(*Nyx).Mark(0x116a140?)
	/home/runner/work/nyx/nyx/modules/go/nyx/nyx.go:547 +0x50
github.com/mooltiverse/nyx/modules/go/nyx.(*Nyx).Publish(0x116a140?)
	/home/runner/work/nyx/nyx/modules/go/nyx/nyx.go:574 +0x50
github.com/mooltiverse/nyx/modules/go/nyx.(*Nyx).Run(0xc000022190?, {0xc2e88f, 0x7})
	/home/runner/work/nyx/nyx/modules/go/nyx/nyx.go:458 +0x245
main.main()
	/home/runner/work/nyx/nyx/modules/go/nyx/main/main.go:120 +0x312
```
And my config:
```yaml
---
preset: "simple"
changelog:
  path: "CHANGELOG.md"
  sections:
    ":sparkles: Features": "^feat$"
    ":bug: Bug Fixes": "^fix$"
    ":memo: Documentation": "^docs$"
    ":lipstick: Styles": "^style$"
    ":white_check_mark: Tests": "^test$"
    ":green_heart: Continuous Integration": "^ci$"
    ":wrench: Chores": "^chore$"
  substitutions:
    "- (?:[a-z]+): (.*)": "- %s"
  template: "CHANGELOG.md.tmpl"
verbosity: "INFO"
scheme: "SEMVER"
initialVersion: "0.1.0"
releaseLenient: true
releasePrefix: "v"
git:
  remotes:
    origin:
      authenticationMethod: "USER_PASSWORD"
      user: "nyx"
      password: "{{#environmentVariable}}GITLAB_TOKEN{{/environmentVariable}}"
releaseTypes:
  enabled:
  - "mainline"
  - "candidate"
  publicationServices:
  - "gitlab"
  items:
    mainline:
      matchBranches: "^(main|master)$"
      gitTag: true
      gitTagMessage: "Release version {{version}}"
      gitPush: true
      publish: true
      description: "{{#fileContent}}CHANGELOG.md{{/fileContent}}"
    candidate:
      matchBranches: "^(develop)$"
      gitTag: true
      gitTagMessage: "Release version {{version}}"
      gitPush: true
      publish: true
      description: "{{#fileContent}}CHANGELOG.md{{/fileContent}}"
      collapseVersions: true
      collapsedVersionQualifier: "{{branch}}"
      identifiers:
      - position: "BUILD"
        qualifier: "{{#short7}}{{releaseScope.finalCommit}}{{/short7}}"
services:
  gitlab:
    type: "GITLAB"
    options:
      BASE_URI: "{{#environmentVariable}}CI_API_V4_URL{{/environmentVariable}}"
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}GITLAB_TOKEN{{/environmentVariable}}"
      REPOSITORY_NAME: "{{#environmentVariable}}CI_PROJECT_NAME{{/environmentVariable}}"
      REPOSITORY_OWNER: "{{#environmentVariable}}CI_PROJECT_NAMESPACE{{/environmentVariable}}"
```

Cheers,
Frederic
