### ISSUE TITLE
`an error occurred when trying to push: unpack error: index-pack abnormal exit` during `nyx mark`

### ISSUE THREAD

**Issue by rrzal** [mooltiverse/nyx#234]
This error only appears in one repo so far (I've been adding nyx to multiple repos gradually, and it is the first time I encounter this issue).
This repo has more files to push and deeper nested directories.
There's a similar issue for go-git recently, but that seems to be only related to GitHub and is already fixed. https://github.com/go-git/go-git/issues/725

I can't find anything useful from the trace log. Is it possible to provide more logging so I can track down the root cause? This error can be caused by so many things:
- [SSH client related](https://stackoverflow.com/questions/35629118/git-push-error-unpack-failed-index-pack-abnormal-exit)
- Some people used `git push --no-thin` to fix the issue [Link](https://stackoverflow.com/questions/39362918/git-push-error-unpack-failed-index-pack-abnormal-exit)
But I feel like this is probably another go-git related issue.

Trace log:
```shell
ime="2023-06-12T16:24:14Z" level=debug msg="attempting push to 'origin' using user name and password credentials."
time="2023-06-12T16:24:14Z" level=debug msg="pushing changes to remote repository 'origin' using username and password"
time="2023-06-12T16:24:14Z" level=debug msg="username and password authentication will use custom authentication options"
an error occurred when trying to push: unpack error: index-pack abnormal exit
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
```

Job config:
```yaml
nyx_mark:
  dependencies:
    - infer_version_nyx
    - infer_version_c_header
    - update_c_version_header
  stage: release
  tags:
    - docker
  image:
    name: mooltiverse/nyx:2.4.4-hotfix219.3
    entrypoint: [""]
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: "0"
  before_script:
    - git config user.name "Linux CI Station"
    - git config user.email "linux.ci.station@example.com"
  script:
    - git checkout -b $CI_COMMIT_BRANCH
    - ls -a
    - git status
    - nyx mark
    - ls -a
    - git status
  except:
    - master
```
