### ISSUE TITLE
Ssh key cannot be used

### ISSUE THREAD

**Issue by DrummyFloyd** [mooltiverse/nyx#288]
here my ssh config for the git sections , dunno where im wrong

```yaml
git:
  remotes:
    origin:
      authenticationMethod: PUBLIC_KEY
      user: DrummyFloyd
      privateKey: ".ssh/id_ed25519" # tried both line
      # privateKey: ~/.ssh/id_ed25519
```
```shell
❯ nyx mark
INFO[0000] Version: '3.1.1'                             
ERRO[0000] cannot instantiate a PublicKeys object using the provided private key: ssh: no key found 
an error occurred when trying to push: ssh: handshake failed: knownhosts: key mismatch
```

any idea what i'm missing?

```shell
yx version: 2.5.2

Usage:
    nyx [arguments] [command]

Commands are:
    clean               reverts the repository to its initial state and removes files created by other commands, if any
    infer               inspects the commit history and repository status and computes the project version
    make                produces artifacts (i.e. changelog) as per the configuration
    mark                commits, tags and pushes, according to the configuration and the repository status
    publish             publish the new release, if any, to the configured services
```

obviously , my ssh key exist, because i'vve clone my repo and work everyday with this key =)

**Comment by sh-cau** [comment]
You don't need to specify a `user` field in that case.
Instead, you need to pass your passphrase like so:
```yaml
git:
  remotes:
    origin:
      authenticationMethod: "PUBLIC_KEY"
      privateKey: "{{#fileContent}}<dirToYourHome/>/.ssh/id_ed25519{{/fileContent}}"
      passphrase: "{{#environmentVariable}}SSH_PASSPHRASE{{/environmentVariable}"
```
and then set the environment variable `SSH_PASSPHRASE` in the shell where you execute nyx. 
Note that this will leave your passphrase readable as plain text in your shell history but it is still better than using, e.g.,
`passphrase: "actualPassphrase"`.
Hope that helps
