### ISSUE TITLE
Nyx erroneosly trying to authenticate using SSH instead of GitLab Access Token

### ISSUE THREAD

**Issue by sh-cau** [mooltiverse/nyx#289]
I setup `nyx` to use a personal access token with permissions `api, read_api, write_repository` and I followed the documentation regarding setting up the `git` and `services:gitlab` fields of the configuration.
However, I always get the error (see especially last line)
```
   10 DEBU[0000] the release type has the git push flag enabled
    9 DEBU[0000] pushing local changes to remotes
    8 DEBU[0000] pushing local changes to remote 'origin'
    7 DEBU[0000] looking up credentials for remote 'origin'
    6 DEBU[0000] using configured credentials for remote 'origin'
    5 DEBU[0000] push force flag is 'false'
    4 DEBU[0000] attempting push to 'origin' using user name and password credentials.
    3 DEBU[0000] pushing changes to remote repository 'origin' using username and password
    2 DEBU[0000] username and password authentication will use custom authentication options
    1 an error occurred when trying to push: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

so it seems nyx is trying to authenticate using `ssh` but I want it to use the token instead. I pass the token as an environment variable.  What am I doing wrong?
See the (relevant parts of the) configuration:

```yaml
--- 
preset: "simple"
releaseTypes:
  enabled: 
   - mainline
  publicationServices:
    - gitlab
  remoteRepositories:
    - origin
  items:
    mainline:
      matchWorkspaceStatus: "CLEAN"
      matchBranches: "^(master|main)$"
      collapseVersions: false 
      gitTag: true
      gitCommit: true 
      gitPush: true 
      publish: true 
git:
  remotes:
    origin:
      authenticationMethod: "USER_PASSWORD"
      user: "PRIVATE-TOKEN"
      password: "{{#environmentVariable}}GITLAB_TOKEN{{/environmentVariable}}"
services:
  gitlab:
    type: "GITLAB"
    options:
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}GITLAB_TOKEN{{/environmentVariable}}"
      REPOSITORY_NAME: "<repositoryName>"
      REPOSITORY_OWNER: "<theOwner>"
```

**Comment by sh-cau** [comment]
As a remark, I am able to push and publish successfully with
```yaml
git:
  remotes:
    origin:
      authenticationMethod: "PUBLIC_KEY"
      privateKey: "{{#fileContent}}<dirToHome/>/.ssh/id_ed25519{{/fileContent}}"
      passphrase: "{{#environmentVariable}}SSH_PASSPHRASE{{/environmentVariable}"
```
