### ISSUE TITLE
Breaking Change section in ChangeLog

### ISSUE THREAD

**Issue by DrummyFloyd** [mooltiverse/nyx#290]
Hi, 
i'm wondering how can i achieve to make a BREAKING_CHANGE section in the CHANGELOG.md, if there is any of those? 

```yaml
changelog:
  # WARNING: dunno why it's not created.. error ?
  # append: "head"
  path: "CHANGELOG.md"
  template: CHANGELOG.tpl
  sections:
    "Added": "^feat$"
    "Fixed": "^fix$"
    "Changed": "^(?!feat|fix).*$"
  # TODO: make Tempalte to use CI_CD vars
  substitutions:
    # need to be repelace with envVAR CI_PROJECT_PATH
    "(?m)#([0-9]+)(?s)": "[#%s](https://gitlab.com/xxx/xxxx-/issues/%s)"
    ```
