### ISSUE TITLE
Regex subsitution not well compiled

### ISSUE THREAD

**Issue by DrummyFloyd** [mooltiverse/nyx#293]
i want to substitue the specific version of chart not all of them  in a `Chart.yaml`
```yaml
apiVersion: v2
name: dummyChart
type: application
version: 1.0.0
appVersion: main
description: dummy
icon: http://gitlab
sources:
  - https://gitlab.com/
deprecated: false
dependencies:
  - name: dummy1
    version: 19.0.8
    repository: dummy1
    condition: dummy1.enabled
```

`.nyx.yaml` => this one **WORK** but change every `version`, in file , which i do not want  => https://regex101.com/r/fJwGfk/1
```yaml
substitutions:
  enabled:
    - helm_version
  items:
    helm_version:
      files: "**/Chart.yaml"
      match: "(\"|')?version(\"|')?(\\s)*:(\\s)*(\"|')?(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?(\"|')?"
      replace: 'version: "{{#capture expression="^[\D]*(?<semver>(?:\d+\.)?(?:\d+\.)?(?:\*|\d+))$" group="semver"}}{{version}}{{/capture}}"'
```

`.nyx.yaml` => this one **DO NOT WORK** the only change is from the regex startLine => `^` from the `match` key =>https://regex101.com/r/cFZayJ/1
```yaml
substitutions:
  enabled:
    - helm_version
  items:
    helm_version:
      files: "**/Chart.yaml"
      match: "/^(\"|')?version(\"|')?(\\s)*:(\\s)*(\"|')?(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?(\"|')?/gm"
      replace: 'version: "{{#capture expression="^[\D]*(?<semver>(?:\d+\.)?(?:\d+\.)?(?:\*|\d+))$" group="semver"}}{{version}}{{/capture}}"'
```

is there a problem in my regex ? or in the code interpolation ? 

EDIT:

seems to be related the options parsed herer
https://github.com/mooltiverse/nyx/blob/56c5e7368385d6411daa469e6b6081a690db4afc/modules/go/nyx/command/make.go#L542

when i force the multinline stuff, everything seems to work fine 
i tried to simplify the regex (taht still match my needs) => https://regex101.com/r/5Dxz71/1
```yaml
substitutions:
  enabled:
    - helm_version
  items:
    helm_version:
      files: "**/Chart.yaml"
      match: "^version:(\\s)*(\"|')?(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?(\"|')?"
      replace: 'version: "{{#capture expression="^[\D]*(?<semver>(?:\d+\.)?(?:\d+\.)?(?:\*|\d+))$" group="semver"}}{{version}}{{/capture}}"'
```

but still nothing i had to make a change on the above code link and change the options to 2 => [check options here](https://github.com/dlclark/regexp2/blob/05e6ac2ab64bbfb3b0ece82156906edbe794b140/regexp.go#L137)
this behaviour is the same even if i add the `/m` option ath end of the regex

dunno if options are well parsed from the regex string .. at this point

**Comment by flelli** [comment]
Hi @DrummyFloyd , it's all about the regex. Try this (remember to escape backslashes):
`^version: (0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$`

**Comment by DrummyFloyd** [comment]
@flelli 
i tried you regex
```yaml
  items:
    helm_version:
      files: "**/Chart.yaml"
      match: "^version: (0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
      replace: 'version: "{{#capture expression="^[\D]*(?<semver>(?:\d+\.)?(?:\d+\.)?(?:\*|\d+))$" group="semver"}}{{version}}{{/capture}}"'
```

even with you regex it's not working as exepcted
=/

**Comment by DrummyFloyd** [comment]
@flelli 
even with the simpliest regex 
=> STILL no work 
```yaml
substitutions:
  enabled:
    - helm_version
  items:
    helm_version:
      files: "**/Chart.yaml"
      match: "^version:" with or without backslash \\^version:
      replace: 'version: "{{#capture expression="^[\D]*(?<semver>(?:\d+\.)?(?:\d+\.)?(?:\*|\d+))$" group="semver"}}{{version}}{{/capture}}"'
```
```shell
nyx make && git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .nyx.yaml
	modified:   CHANGELOG.md
```
=> WORK ..
```yaml
substitutions:
  enabled:
    - helm_version
  items:
    helm_version:
      files: "**/Chart.yaml"
      match: "version:"
      replace: 'version: "{{#capture expression="^[\D]*(?<semver>(?:\d+\.)?(?:\d+\.)?(?:\*|\d+))$" group="semver"}}{{version}}{{/capture}}"'
```
```shell
nyx make && git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .nyx.yaml
	modified:   CHANGELOG.md
	modified:   charts/initiative-cloud/Chart.yaml
```
seems pretty related to the `^` character

**Comment by DrummyFloyd** [comment]
should make something like this to make it work 

```yaml
substitutions:
  enabled:
    - helm_version
  items:
    helm_version:
      files: "**/Chart.yaml"
      match: "\\n(\"|')?version(\"|')?(\\s)*:(\\s)*(\"|')?(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?(\"|')?"
      replace: >-

        version: "{{#capture expression="^[\D]*(?<semver>(?:\d+\.)?(?:\d+\.)?(?:\*|\d+))$" group="semver"}}{{version}}{{/capture}}"
```

thank you for your time !
