### ISSUE TITLE
Gradle plugin produces an empty changelog on a selfhosted gitlab instance

### ISSUE THREAD

**Issue by cbrani** [mooltiverse/nyx#320]
I set up a demo project to test semantic versioning with NYX. After a lot of tries (and reading other issues and posts) I figured out which settings I need to set for gitlab on an selfhosted instance.

I'm using gradle 8.8 and the newest gradle plugin of nyx.

My problem is that I need to split up the the phase of nyx in different jobs. I have an infer job and here I call nyxMake which generates a proper changelog. So far so good.

But if I call any further phase job (next is nyxMark) I get an empty changelog. That's why I changed the CI job to call nyxClean and nyxMake a second time to figure out when the empty changelog appears.
The version number is still correctly calculated by the way.
I attached all the configuration and output files of first and second nyxMake call.
[CHANGELOG-make1.md](https://github.com/user-attachments/files/16195893/CHANGELOG-make1.md)
[CHANGELOG-make2.md](https://github.com/user-attachments/files/16195889/CHANGELOG-make2.md)
[nyx-state-make2.json](https://github.com/user-attachments/files/16195991/nyx-state-make2.json)
[nyx-state-make1.json](https://github.com/user-attachments/files/16195989/nyx-state-make1.json)

And if I use the resume flag it make matters even worse because then the nyxMark task complains about not being able to read the state file.
```
./gradlew nyxMark
FAILURE: Build failed with an exception.
* What went wrong:
Failed to notify build listener.
> Unable to unmarshal content from file '/builds/acme/test/dsloader-demo/build/.nyx-state.json'
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org/.
BUILD FAILED in 719ms
```

I hope someone can shed some light on this. Maybe I forgot something important.

Nyx configuration
```yaml
preset: extended

changelog:
  path: "build/CHANGELOG.md"
  template: "config/nyx/CHANGELOG.tpl"
  sections:
    "Added": "^feat$"
    "Fixed": "^fix$"
  substitutions:
    "(?m)#([0-9]+)(?s)": "[#%s]({{#environmentVariable}}CI_PROJECT_URL{{/environmentVariable}}/-/issues/%s)"

commitMessageConventions:
  enabled: [ conventionalCommits ]

stateFile: "build/.nyx-state.json"
#resume: true

git:
  remotes:
    origin:
      user: "PRIVATE-TOKEN"
      password: "{{#environmentVariable}}GITLAB_TOKEN{{/environmentVariable}}"

releaseTypes:
  enabled:
    - mainline
    - branch
    - internal
  publicationServices:
    - gitlab
  remoteRepositories:
    - origin
  items:
    mainline:
      collapseVersions: false
      description: "{{#fileContent}}build/CHANGELOG.md{{/fileContent}}"
      filterTags: "^()?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)$"
      gitCommit: "true"
      gitCommitMessage: "Release version {{version}}"
      gitPush: "{{#environmentVariable}}CI{{/environmentVariable}}"
      gitTag: "{{#environmentVariable}}CI{{/environmentVariable}}"
      gitTagMessage: "Tag version {{version}}"
      matchBranches: ^(master|main)$
      matchEnvironmentVariables:
        CI: "^true$"
      matchWorkspaceStatus: "CLEAN"
      publish: "{{#environmentVariable}}CI{{/environmentVariable}}"
      versionRangeFromBranchName: false
    branch:
      collapseVersions: true
      collapsedVersionQualifier: "{{#upper}}{{#capture expression=\".*\\/([0-9a-zA-Z-_]+)$\" group=1}}{{#environmentVariable}}CI_COMMIT_REF_NAME{{/environmentVariable}}{{/capture}}{{/upper}}"
      description: "Feature release {{version}}"
      filterTags: "^({{configuration.releasePrefix}})?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)((([0-9a-zA-Z-_]*)(\\.([0-9]\\d*))?)?)$"
      gitCommit: "false"
      gitPush: "false"
      gitTag: "false"
      matchEnvironmentVariables:
        CI_COMMIT_REF_NAME: ".*(feature|bugfix|improvement)((-|\\/)[0-9a-zA-Z-_]+)?$"
      publish: "false"
      publishPreRelease: "true"
      versionRangeFromBranchName: false
    internal:
      collapseVersions: true
      collapsedVersionQualifier: "SNAPSHOT"
      description: "{{#fileContent}}build/CHANGELOG.md{{/fileContent}}"
      gitCommit: "false"
      gitPush: "false"
      gitTag: "false"
      identifiers:
        -
          qualifier: "{{#sanitizeLower}}{{branch}}{{/sanitizeLower}}"
          position: "BUILD"
        -
          qualifier: "{{#short5}}{{releaseScope.finalCommit}}{{/short5}}"
          position: "BUILD"
        -
          qualifier: "{{#timestampYYYYMMDDHHMMSS}}{{timestamp}}{{/timestampYYYYMMDDHHMMSS}}"
          position: "BUILD"
      publish: "false"
      versionRangeFromBranchName: false

scheme: SEMVER

services:
  gitlab:
    type: GITLAB
    options:
      BASE_URI: "{{#environmentVariable}}CI_API_V4_URL{{/environmentVariable}}"
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}GITLAB_TOKEN{{/environmentVariable}}"
      REPOSITORY_NAME: "{{#environmentVariable}}CI_PROJECT_NAME{{/environmentVariable}}"
      REPOSITORY_OWNER: "{{#environmentVariable}}CI_PROJECT_NAMESPACE{{/environmentVariable}}"

```

gitlab ci config
```yaml
default:
  tags:
    - runner1

stages:
  - Infer
  - Release

.gradle_nyx:
  image:
    name: docker.io/library/eclipse-temurin:$JAVA_VERSION
    pull_policy: always
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - |
      if ! (which git >/dev/null) || ! (which git-lfs >/dev/null); then
        if (which apt >/dev/null); then
          apt-get update >/dev/null
          apt-get install -y --no-install-recommends git git-lfs jq >/dev/null
          echo "installed git, git-lfs, and jq"
        else
          echo "Unable to find git and git-lfs, and unable to detect os to automatically install it" >&2
          exit 1
        fi
      fi
    - |
      if [ -n "$CI_COMMIT_BRANCH" ]; then
        git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
      fi

infer:
  extends: .gradle_nyx
  stage: Infer
  script:
    - './gradlew nyxClean clean'
    - mkdir build
    - './gradlew nyxMake'
    - 'jq -r "{NYX_VERSION: .version, NYX_NEW_VERSION: .newVersion, NYX_NEW_RELEASE: .newRelease} | to_entries[] | join(\"=\")" "build/.nyx-state.json" > "build/.nyx-state.env"'
    - 'jq -C "{NYX_VERSION: .version, NYX_NEW_VERSION: .newVersion, NYX_NEW_RELEASE: .newRelease}" "build/.nyx-state.json"'
    - 'mv "build/.nyx-state.json" "build/nyx-state-make1.json"'
    - |
      if [ -f "build/CHANGELOG.md" ]; then
        mv "build/CHANGELOG.md" "build/CHANGELOG-make1.md"
      fi
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - "**/build"
      - .gradle
  artifacts:
    paths:
      - "build/.nyx-state*.json"
      - "build/.nyx-state.env"
      - "build/*.md"
    reports:
      dotenv:
        - "build/.nyx-state.env"

release-version:
  extends: .gradle_nyx
  stage: Release
  needs:
    - infer
  script:
    - |
      if [ ! $NYX_NEW_RELEASE = true ]; then
        echo "No need to release, bye!"
        exit 0
      fi
    - echo "running job release-version for $NYX_VERSION"
    - git remote set-url origin "https://PRIVATE-TOKEN:$GITLAB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
    #- git config "lfs.https://PRIVATE-TOKEN:$GITLAB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git/info/lfs.locksverify" true
    - './gradlew nyxClean'
    - './gradlew nyxInfer nyxMake'
    - |
      cp build/.nyx-state.json build/.nyx-state-make2.json
      cp build/CHANGELOG.md build/CHANGELOG-make2.md
    - './gradlew --debug --stacktrace nyxMark > build/gradle-mark.log 2>&1'
    - './gradlew nyxMark'
    - |
      cp build/.nyx-state.json build/.nyx-state-mark.json
      cp build/CHANGELOG.md build/CHANGELOG-mark.md
    - './gradlew --debug --stacktrace nyxPublish > build/gradle-publish.log 2>&1'
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - 'build/.nyx-state*.json'
      - 'build/*.log'
      - 'build/*.md'
      - .git/config
  rules:
    - if: '$CI_MERGE_REQUEST_ID'
      when: never
    - if: $CI_COMMIT_TAG
      when: never                                  # Do not run this job when a tag is created manually
    - when: on_success

variables:
  DOCKER_TLS_CERTDIR: ""  # https://gitlab.com/gitlab-org/gitlab-runner/issues/4501

  POSTGRES_ENABLED: "false"
  STAGING_ENABLED: "true"

  # Ensure that tags are retrieved from git repository otherwise the release
  # Gradle plugin will not be able to create the next version number:
  #GIT_FETCH_EXTRA_FLAGS: --tags
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"
```

**Comment by flelli** [comment]
Hi @cbrani , sorry to hear that. Can you please provide some Nyx debug output?

**Comment by cbrani** [comment]
Hi @flelli, of course.

The first log is with the resume flag activated.
[gradle-mark-resume.log](https://github.com/user-attachments/files/16201948/gradle-mark-resume.log)

The following logs are with the resume flag deactived.
Next try was nyxMark and nyxPublish in separated calls. Task nyxMark was executed successful but with the empty changelog.
[gradle-mark.log](https://github.com/user-attachments/files/16201952/gradle-mark.log)
And nyxPublish complaint that it can't create tag because it already exists
[gradle-publish.log](https://github.com/user-attachments/files/16201954/gradle-publish.log)
 
Last try I skipped the extra call of task nyxMark and just let nyxPublish run. Which succeeded but empty changelog
[gradle-publish-success.log](https://github.com/user-attachments/files/16201961/gradle-publish-success.log)
and resulting state file and changelog file
[nyx-state-publish.json](https://github.com/user-attachments/files/16201976/nyx-state-publish.json)
[CHANGELOG.md](https://github.com/user-attachments/files/16201977/CHANGELOG.md)

**Comment by flelli** [comment]
Hi @cbrani ,

The state files you attached in the first post ([nyx-state-make1.json](https://github.com/user-attachments/files/16195989/nyx-state-make1.json) and [nyx-state-make2.json](https://github.com/user-attachments/files/16195991/nyx-state-make2.json)) have exactly the same content so I guess there was a mistake when attaching them? I mistakenly didn't notice this in the first place but it would be useful to see the difference. 

However I guess the real issue here is the `resume` option, which is unable to load the state from previous runs.
I know your use case needs to run separate commands at different stages but for the sake of testing it could be useful to see the behavior if you run Infer, Make and Mark in the same Gradle command or at least in the same stage of the pipeline.

I'm afraid the issue here is making the state file produced in the first stage to the second. I'm a little rusty on GitLab pipelines but as far as I remember your pipeline looks ok. However there must be something with the state file. Another test could be checking the contents of the state file when the second stage starts, making sure it's the same as the output from the first one, also making sure it's readable/writeable by Nyx.

When Nyx tries to tag and shows an error due to an existing tag that's ok, as there is already a tag with the same name in the repository. Sometimes this happens when the tag is not _visible_ going back in the commit history (i.e. it's ona commit in another branch). However, if you consider the tag as a _floating_ one, you can [force](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/release-types/#git-tag-force) it.

**Comment by cbrani** [comment]
you are right. This one is the real nyx-state-make1.json
[nyx-state-make1.json](https://github.com/user-attachments/files/16202210/nyx-state-make1.json)

**Comment by cbrani** [comment]
Hi @flelli ,
I made a copy at the beginning of the second job. It's nyx-state-make1-1.json.
This time the task nyxMark didn't complete successful.

All the files are in the zip now.
[Archive.zip](https://github.com/user-attachments/files/16203049/Archive.zip)

**Comment by flelli** [comment]
As far as I understand the failure is due to the Git tag already present. Can you confirm?

**Comment by cbrani** [comment]
yes, I can confirm

**Comment by flelli** [comment]
So, provided this is a different issue that you can handle with the `force` option as explained above, this proves that the problem is on the Nyx state when it's passed among stages.

You need to make sure that, when the second stage starts the Nyx state is exactly what was produced by the first stage.

**Comment by cbrani** [comment]
I made some more tests.

1. Test: everything in one job with separate nyx task calls.
```yaml
release-version:
  extends: .gradle_nyx
  stage: Release
  needs:
    - job: infer
      optional: true
  script:
    #- git config "lfs.https://PRIVATE-TOKEN:$GITLAB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git/info/lfs.locksverify" true
    - './gradlew nyxMake'
    - |
      cp build/.nyx-state.json build/nyx-state-make.json
      cp build/CHANGELOG.md build/CHANGELOG-make.md
    - git remote set-url origin "https://PRIVATE-TOKEN:$GITLAB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
    - './gradlew --debug --stacktrace nyxMark > build/gradle-mark.log 2>&1'
    - |
      cp build/.nyx-state.json build/nyx-state-mark.json
      cp build/CHANGELOG.md build/CHANGELOG-mark.md
    - './gradlew --debug --stacktrace nyxPublish > build/gradle-publish.log 2>&1'
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - 'build/*.json'
      - 'build/*.log'
      - 'build/*.md'
      - .git/config
  rules:
    - if: '$CI_MERGE_REQUEST_ID'
      when: never
    - if: $CI_COMMIT_TAG
      when: never                                  # Do not run this job when a tag is created manually
    - when: on_success
```
Result: correct changelog, tag was create but no release was published
[Archive-04.zip](https://github.com/user-attachments/files/16228154/Archive-04.zip)


2. Test: only one call of nyxPublish
```yaml
release-version:
  extends: .gradle_nyx
  stage: Release
  needs:
    - job: infer
      optional: true
  script:
    #- git config "lfs.https://PRIVATE-TOKEN:$GITLAB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git/info/lfs.locksverify" true
    - git remote set-url origin "https://PRIVATE-TOKEN:$GITLAB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
    - './gradlew --debug --stacktrace nyxPublish > build/gradle-publish.log 2>&1'
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - 'build/*.json'
      - 'build/*.log'
      - 'build/*.md'
      - .git/config
  rules:
    - if: '$CI_MERGE_REQUEST_ID'
      when: never
    - if: $CI_COMMIT_TAG
      when: never                                  # Do not run this job when a tag is created manually
    - when: on_success
```
Result: correct changelog, tag was created and the release was published
[Archive-05.zip](https://github.com/user-attachments/files/16228156/Archive-05.zip)
