### ISSUE TITLE
"extended" preset doesn't seem to have pre-configured services

### ISSUE THREAD

**Issue by neilime** [mooltiverse/nyx#352]
Hi,

In documentation (https://mooltiverse.github.io/nyx/docs/user/configuration-presets/extended#services) it says that `extended` preset: "The [GitHub](https://github.com/) and [GitLab](https://gitlab.com/) services are available with this preset"

But it seem that is not the case, when using nyx with  `releaseTypesPublicationServices: github` there is the following error:

>  the release type uses the 'github' publication service but no such service has been configured in the 'services' section

When looking at the code (https://github.com/mooltiverse/nyx/blob/main/src/go/nyx/configuration/presets_extended.go), I dont see where services are included

**Comment by flelli** [comment]
You're right @neilime , I'll fix it.

**Comment by neilime** [comment]
Thank you for your responsiveness @flelli, do you plan to release this fix soon?

**Comment by flelli** [comment]
It's already cooking [here](https://github.com/mooltiverse/nyx/actions/runs/12790816959).

**Comment by neilime** [comment]
@flelli I've tested with the new version, it does not work entirely:

It seams that the "AUTHENTICATION_TOKEN" options is not preconfigured.

GitHub workflow:

```yml
    - id: nyx
      uses: mooltiverse/nyx@main
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        NYX_GIT_REMOTES_origin_AUTHENTICATION_METHOD: USER_PASSWORD
        NYX_GIT_REMOTES_origin_USER: ${{ inputs.token }}
        NYX_GIT_REMOTES_origin_PASSWORD: ${{ inputs.token }}

        NYX_SERVICES_github_TYPE: GITHUB
        NYX_SERVICES_github_OPTIONS_REPOSITORY_NAME: ${{ github.event.repository.name }}
        NYX_SERVICES_github_OPTIONS_REPOSITORY_OWNER: ${{ github.repository_owner }}
      with:
        verbosity: "DEBUG" # For test purpose only
        command: publish
        preset: "extended"
        releaseLenient: false
        releaseTypesEnabled: "mainline"
        releaseTypesPublicationServices: "github"
```

Logs: 

```
level=debug msg="instantiating service 'github' of type 'GITHUB' with '2' options"
level=debug msg="resolving templates for '2'"
level=debug msg="no custom URI passed to the 'GitHub' service, the default endpoint will be used"
level=warning msg="no authentication token passed to the 'GitHub' service, no authentication protected operation will be available. Use the 'AUTHENTICATION_TOKEN' option to set this value"
```

If I force the service configuration, it works:

GitHub workflow:

```yml
    - id: nyx
      uses: mooltiverse/nyx@main
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        NYX_GIT_REMOTES_origin_AUTHENTICATION_METHOD: USER_PASSWORD
        NYX_GIT_REMOTES_origin_USER: ${{ inputs.token }}
        NYX_GIT_REMOTES_origin_PASSWORD: ${{ inputs.token }}

        NYX_SERVICES_github_TYPE: GITHUB
        NYX_SERVICES_github_OPTIONS_REPOSITORY_NAME: ${{ github.event.repository.name }}
        NYX_SERVICES_github_OPTIONS_REPOSITORY_OWNER: ${{ github.repository_owner }}
        NYX_SERVICES_github_OPTIONS_AUTHENTICATION_TOKEN: "{{#environmentVariable}}GITHUB_TOKEN{{/environmentVariable}}"
      with:
        verbosity: "DEBUG" # For test purpose only
        command: publish
        preset: "extended"
        releaseLenient: false
        releaseTypesEnabled: "mainline"
        releaseTypesPublicationServices: "github"
```
