### ISSUE TITLE
GitLab publish fails with 422 "ref not specified" when running Nyx via Docker in GitLab CI

### ISSUE THREAD

**Issue by eyarb** [mooltiverse/nyx#368]
**Description:**
I'm encountering an issue when running nyx publish inside a GitLab CI job using the official Docker image (mooltiverse/nyx:3.1.3). Even though nyx mark shows that a tag is created and pushed, publish fails with:
`could not publish GitLab release with tag 'component-v0.2.0': 422 {message: Ref is not specified}`

**Environment:**
- CI provider: GitLab CI
- Git strategy: clone
- Git depth: 0
- Nyx image: mooltiverse/nyx:3.1.3
- Execution context: Inside a Docker container in GitLab CI
- The job is running in a MR pipeline

**What I’ve tried:**

1. Confirmed that nyx mark creates the tag and reports pushing it:

```
tag 'component-v0.2.0' applied to commit 'abc123'
local changes pushed to remote 'origin'
```

2. Verified that git tag -l does not list the new tag after mark, even though the logs say it was created.

3. GitLab release fails because the tag isn't pushed or recognized.

4. Checked that .git is fully present and HEAD is valid.

5. Tried switching to a named branch using git checkout -B ci-temp-branch.

**nyx.yml snippet:**

```
preset: simple
scheme: "SEMVER"
releaseLenient: true
verbosity: "DEBUG"
intialVersion: "0.22.2"
releasePrefix: "component-v"

git:
  remotes:
    origin:
      authenticationMethod: USER_PASSWORD

releaseTypes:
  enabled:
    - mainline
    - internal
  publicationServices: 
    - gitlab
  remoteRepositories:
    - origin
  items:
    mainline:
      collapseVersions: false
      gitCommit: "false"
      gitPush: "true"
      gitTag: "true"
      gitTagForce: "true"
      gitPushForce: "true"
      gitTagMessage: "Release component v{{version}}"
      gitTagNames:
        - "{{version}}"
      publish: "true"
      filterTags: ^({{configuration.releasePrefix}})?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)$"
      matchWorkspaceStatus: "CLEAN"
      matchBranches: ^(master|main)$
      versionRangeFromBranchName: false
    internal:
      collapseVersions: true
      collapsedVersionQualifier: "{{#sanitizeLower}}{{branch}}{{/sanitizeLower}}"
      gitCommit: "false"
      gitPush: "true"
      gitTag: "true"
      gitTagForce: "true"
      gitPushForce: "true"
      gitTagMessage: "Release Internal component v{{version}}"
      gitTagNames:
        - "{{version}}"
      publish: "true"
      filterTags: ^({{configuration.releasePrefix}})?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)$"
      matchWorkspaceStatus: "CLEAN"
      matchBranches: "^(alpha|beta|gamma|delta|epsilon|zeta|eta|theta|iota|kappa|lambda|mu|nu|xi|omicron|pi|rho|sigma|tau|upsilon|phi|chi|psi|omega|poc).*$"
      versionRangeFromBranchName: false

services:
  gitlab:
    type: "GITLAB"
    options:
      BASE_URI: "https://OUR_GITLAB_URL/api/v4"
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}GITLAB_NYX_TOKEN{{/environmentVariable}}"
      REPOSITORY_NAME: "OUR_REPONAME"
      REPOSITORY_OWNER: "OUR_GROUP"
```

**.gitlab-ci.yml snippet:**

```
.nyx-base-template:
  image:
    name: ${REGISTRY}/mooltiverse/nyx:3.1.3
    entrypoint: [""]
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: "0"

nyx-release-template:
  extends: .nyx-base-template
  stage: release
  variables:
    NYX_GIT_REMOTES_origin_USER: $GITLAB_NYX_USER
    NYX_GIT_REMOTES_origin_PASSWORD: $GITLAB_NYX_TOKEN
  before_script:
    - git remote set-url origin "${CI_SERVER_URL}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git"
    - git checkout -B "$CI_COMMIT_REF_NAME"
    - git config --global user.email "nyx@bot.com"
    - git config --global user.name "bot-nyx"
  script:
    - nyx publish --services-gitlab-options-AUTHENTICATION_TOKEN="${GITLAB_NYX_TOKEN}"
```

**Expected behavior:**

- `nyx mark` should create and push the tag.

- `nyx publish` should create the GitLab release referencing the tag.

**Actual behavior:**

- `mark` reports success, but tag does not show up in git tag -l.

- `publish` fails with 422 due to missing ref.

**Questions:**

Is there a missing config/setup step I'm overlooking?
